site_name: 🧠
site_url: https://jasper-zanjani.github.io/notes
site_dir: site
theme:
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: yellow

  
  shortcuts:
    search: 191

markdown_extensions:
  - abbr
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.emoji: # from https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#emoji
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
