site_name: 🧠
site_url: https://jasper-zanjani.github.io/notes
site_dir: site
theme:
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: yellow

  
  shortcuts:
    search: 191
extra_css:
- style/admonitions-gcp.css
- style/admonitions-azure.css
- style/admonitions-aws.css
- style/admonitions-rs.css
- style/admonitions-cs.css
- style/admonitions-py.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji: # from https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#emoji
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
