site_name: 🧠
site_url: https://jasper-zanjani.github.io/notes
site_dir: site
theme:
  name: material
  palette:
    scheme: slate
    primary: amber
    accent: yellow
  features:
    - navigation.tabs         # Render top-level sections as a menubar
  # - navigation.tabs.sticky  # Top-level menubar remains visible while scrolling down
  # - navigation.indexes      # Integrate section index pages into sections as overview pages (incompatible with toc.integrate)
    - navigation.sections     # Render sections as groups
    - navigation.expand       # Expand all collapsible subsections by default
    - toc.integrate           # Always render table of contents as part of the left navbar
    - content.code.annotate
  
  shortcuts:
    search: 191
extra_css:
- style/admonitions-gcp.css
- style/admonitions-azure.css
- style/admonitions-aws.css
- style/admonitions-rs.css
- style/admonitions-cs.css
- style/admonitions-cpp.css
- style/admonitions-cisco.css
- style/admonitions-py.css
- style/admonitions-output.css

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - meta
  - pymdownx.details
  - pymdownx.emoji: # from https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#emoji
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist
